const api = require('../../utils/api');
const features = require('../../utils/features');
const subjectMap = {语文:'人文社科',数学:'数理逻辑',英语:'外语学习',物理:'数理逻辑',化学:'数理逻辑',生物:'数理逻辑',政治:'人文社科',历史:'人文社科',地理:'人文社科'};
const teachers = [['曹嘉芸','数学','中级','曹','p1'],['王晨潞','数学','中级','王','p2'],['吴培铃','数学','中级','吴','p3'],['朱苏辰','物理','高级','朱','p4'],['睡觉呼呼呼.','物理','中级','睡','p5'],['吴万捷','物理','初级','吴','p1'],['常青藤','物理','初级','常','p2'],['沈冰','化学','中级','沈','p3'],['半截的诗','化学','中级','诗','p4'],['王萱','化学','中级','王','p5'],['波月波月','化学','初级','波','p1'],['云淡风轻','化学','初级','云','p2'],['仓仓仓','地理','高级','仓','p3']].map(([name, rawSubject, level, avatar, color]) => ({ name, subject:subjectMap[rawSubject], level, avatar, color, school:'学校及专业：略', payment:'收费方式：略', tags:[subjectMap[rawSubject]], intro:'略' }));
const stars = level => level === '高级' ? '★★★' : level === '中级' ? '★★☆' : '★☆☆';
const accountTitles = { payments:'缴费信息', appointments:'我的预约', favorites:'收藏的交流者', settings:'账户设置' };

Page({
  data: { ...features.initialData, page:'home', queryInput:'', subjectFilter:'all', levelFilter:'all', subjects:['人文社科','数理逻辑','外语学习','艺术素养'], levels:['初级','中级','高级'], filteredTeachers:[], loggedIn:false, user:{}, avatarSrc:'', showLoginPanel:false, agreementAccepted:false, loginNickname:'', loginPhone:'', loginCode:'', codeCountdown:0, showTeacherModal:false, selectedTeacher:{}, consultSent:false, favoriteActive:false, showRegisterPanel:false, registerSuccess:false, idCardName:'', studentIdName:'', teacherPhone:'', featureTitle:'', featureHeading:'', featureDescription:'', featureIconSrc:'', accountMode:'', accountItems:[], paymentAmount:'', settingNickname:'', agentCards:[{title:'学习规划助手',desc:'根据年级、目标和可用时间生成学习计划。',iconSrc:'/assets/icon-agents.png'},{title:'作业答疑助手',desc:'举例：整理错题重点，并推荐下一步练习方向。',iconSrc:'/assets/icon-courses.png'},{title:'英语陪练助手',desc:'举例：模拟日常对话，给出口语表达建议。',iconSrc:'/assets/icon-consult.png'}], shortcuts:[{label:'网课',page:'courses',iconSrc:'/assets/icon-courses.png'},{label:'咨询',page:'consult',iconSrc:'/assets/icon-consult.png'},{label:'Agents',page:'agents',iconSrc:'/assets/icon-agents.png'},{label:'视频',page:'videos',iconSrc:'/assets/icon-videos.png'},{label:'群组',page:'groups',iconSrc:'/assets/icon-groups.png'}] },
  onLoad() { this.allTeachers = teachers.map(teacher => ({ ...teacher, stars:stars(teacher.level) })); this.filterTeachers(); if (wx.getStorageSync(api.tokenKey)) this.loadMe(); },
  onUnload() { clearInterval(this.codeTimer); },
  notice(error) { wx.showToast({ title:error.message || error, icon:'none' }); },
  async loadMe() { try { const result = await api.request('/api/me'); this.applyUser(result.user); } catch { wx.removeStorageSync(api.tokenKey); } },
  applyUser(user) { this.setData({ loggedIn:true, user, avatarSrc:api.imageUrl(user.avatarUrl), settingNickname:user.nickname }); },
  filterTeachers() { const { subjectFilter, levelFilter, queryInput } = this.data; const query = queryInput.trim().toLowerCase(); this.setData({ filteredTeachers:this.allTeachers.filter(teacher => (subjectFilter === 'all' || teacher.subject === subjectFilter) && (levelFilter === 'all' || teacher.level === levelFilter) && `${teacher.name}${teacher.school}${teacher.subject}`.toLowerCase().includes(query)) }); },
  onQueryInput(event) { this.setData({ queryInput:event.detail.value }); }, onSearch() { this.filterTeachers(); },
  setSubject(event) { this.setData({ subjectFilter:event.currentTarget.dataset.filter }, () => this.filterTeachers()); }, setLevel(event) { this.setData({ levelFilter:event.currentTarget.dataset.filter }, () => this.filterTeachers()); },
  switchPage(event) { this.setData({ page:event.currentTarget.dataset.page, accountMode:'' }); }, goHome() { this.setData({ page:'home', accountMode:'' }); }, goProfile() { this.setData({ page:'profile', accountMode:'' }); }, goBack() { this.data.accountMode ? this.goProfile() : this.goHome(); },
  openFeature(event) { const page = event.currentTarget.dataset.page; const views = { courses:['网课','本周精选课程','语文阅读、数学思维、英语口语等课程将展示在这里。','/assets/icon-courses.png'], consult:['咨询','学习咨询','可在这里提交学科、年级与学习目标，由顾问协助匹配。','/assets/icon-consult.png'], agents:['Agents','','',''], videos:['视频','学习视频','课程回放与公开学习内容将展示在这里。','/assets/icon-videos.png'], groups:['群组','学习群组','同学、老师与家长的学习交流空间将展示在这里。','/assets/icon-groups.png'] }; const view = views[page]; this.setData({ page, accountMode:'', featureTitle:view[0], featureHeading:view[1], featureDescription:view[2], featureIconSrc:view[3] }); },
  showTeacher(event) { const selectedTeacher = this.data.filteredTeachers[event.currentTarget.dataset.index]; this.setData({ selectedTeacher, showTeacherModal:true, consultSent:false, favoriteActive:false }); if (this.data.loggedIn) this.loadFavoriteState(selectedTeacher.name); }, hideTeacher() { this.setData({ showTeacherModal:false }); }, stopPropagation() {},
  async loadFavoriteState(name) { try { const result = await api.request('/api/favorites'); this.setData({ favoriteActive:result.items.some(item => item.teacherName === name) }); } catch (error) { this.notice(error); } },
  async consultTeacher() { if (!this.data.loggedIn) return this.showLogin(); try { await api.request('/api/appointments', 'POST', { teacherName:this.data.selectedTeacher.name }); this.setData({ consultSent:true }); wx.showToast({ title:'已加入我的预约', icon:'success' }); } catch (error) { this.notice(error); } },
  async toggleFavorite() { if (!this.data.loggedIn) return this.showLogin(); try { const result = await api.request('/api/favorites/toggle', 'POST', { teacherName:this.data.selectedTeacher.name }); this.setData({ favoriteActive:result.active }); wx.showToast({ title:result.active ? '已收藏' : '已取消收藏', icon:'success' }); } catch (error) { this.notice(error); } },
  showLogin() { this.setData({ showLoginPanel:true, agreementAccepted:false }); }, hideLogin() { this.setData({ showLoginPanel:false }); }, onAgreementChange(event) { this.setData({ agreementAccepted:(event.detail.value || []).includes('agreed') }); }, requireAgreement() { if (!this.data.agreementAccepted) { this.notice('请先阅读并同意用户协议和隐私政策'); return false; } return true; }, onNickname(event) { this.setData({ loginNickname:event.detail.value }); }, onPhone(event) { this.setData({ loginPhone:event.detail.value }); }, onCode(event) { this.setData({ loginCode:event.detail.value }); },
  async sendCode() { if (this.data.codeCountdown) return; if (!/^1\d{10}$/.test(this.data.loginPhone)) return this.notice('请输入正确手机号'); try { const result = await api.request('/api/auth/code', 'POST', { phone:this.data.loginPhone }); this.setData({ codeCountdown:60, loginCode:result.debugCode || this.data.loginCode }); wx.showToast({ title:result.debugCode ? `测试验证码：${result.debugCode}` : '验证码已发送', icon:'none', duration:3000 }); clearInterval(this.codeTimer); this.codeTimer = setInterval(() => { const next = this.data.codeCountdown - 1; if (next <= 0) { clearInterval(this.codeTimer); this.setData({ codeCountdown:0 }); } else this.setData({ codeCountdown:next }); }, 1000); } catch (error) { this.notice(error); } },
  async submitLogin() { try { const result = await api.request('/api/auth/login', 'POST', { nickname:this.data.loginNickname, phone:this.data.loginPhone, code:this.data.loginCode }); wx.setStorageSync(api.tokenKey, result.token); this.applyUser(result.user); this.setData({ showLoginPanel:false }); wx.showToast({ title:'登录成功', icon:'success' }); } catch (error) { this.notice(error); } },
  finishLogin(result) { wx.setStorageSync(api.tokenKey, result.token); this.applyUser(result.user); this.setData({ showLoginPanel:false }); wx.showToast({ title:'登录成功', icon:'success' }); },
  async wechatQuickLogin() { if (!this.requireAgreement()) return; try { const result = await getApp().loginByWechat(); this.finishLogin(result); } catch (error) { this.notice(error); } },
  async onPhoneQuickLogin(event) { if (!this.requireAgreement()) return; if (!event.detail || !event.detail.code) return this.notice('未授权手机号'); try { this.finishLogin(await api.request('/api/auth/phone', 'POST', { code:event.detail.code })); } catch (error) { this.notice(error); } },
  showRegister() { if (!this.data.loggedIn) return this.showLogin(); this.setData({ showRegisterPanel:true, registerSuccess:false }); }, hideRegister() { this.setData({ showRegisterPanel:false }); }, chooseIdCard() { wx.chooseImage({ count:1, sourceType:['camera','album'], success:result => this.setData({ idCardName:result.tempFiles[0].name || '证件照已选择' }) }); }, chooseStudentId() { wx.chooseMessageFile({ count:1, type:'file', success:result => this.setData({ studentIdName:result.tempFiles[0].name || '学籍证明已选择' }) }); }, onTeacherPhone(event) { this.setData({ teacherPhone:event.detail.value }); },
  async submitRegister() { try { await api.request('/api/exchangers', 'POST', { idCardName:this.data.idCardName, studentIdName:this.data.studentIdName, phone:this.data.teacherPhone }); this.setData({ registerSuccess:true }); } catch (error) { this.notice(error); } },
  async openAccount(event) { if (!this.data.loggedIn) return this.showLogin(); const accountMode = event.currentTarget.dataset.mode; this.setData({ page:`account-${accountMode}`, accountMode, featureTitle:accountTitles[accountMode], accountItems:[], paymentAmount:'' }); if (accountMode !== 'settings') await this.loadAccountItems(accountMode); },
  async loadAccountItems(mode = this.data.accountMode) { const endpoint = { payments:'/api/payments', appointments:'/api/appointments', favorites:'/api/favorites' }[mode]; if (!endpoint) return; try { const result = await api.request(endpoint); this.setData({ accountItems:result.items }); } catch (error) { this.notice(error); } },
  onPaymentAmount(event) { this.setData({ paymentAmount:event.detail.value }); },
  async addPayment() { try { await api.request('/api/payments', 'POST', { amount:this.data.paymentAmount, title:'学习服务' }); this.setData({ paymentAmount:'' }); await this.loadAccountItems('payments'); wx.showToast({ title:'沙箱支付演示完成', icon:'success' }); } catch (error) { this.notice(error); } },
  onSettingNickname(event) { this.setData({ settingNickname:event.detail.value }); },
  async saveSettings() { try { const result = await api.request('/api/me', 'PATCH', { nickname:this.data.settingNickname }); this.applyUser(result.user); wx.showToast({ title:'设置已保存', icon:'success' }); } catch (error) { this.notice(error); } },
  chooseAvatar() { wx.chooseImage({ count:1, sizeType:['compressed'], sourceType:['album','camera'], success:async result => { try { const uploaded = await api.uploadAvatar(result.tempFilePaths[0]); this.applyUser(uploaded.user); wx.showToast({ title:'头像已更新', icon:'success' }); } catch (error) { this.notice(error); } } }); },
  async logout() { try { await api.request('/api/auth/logout', 'POST'); } catch (_) {} wx.removeStorageSync(api.tokenKey); this.setData({ loggedIn:false, user:{}, avatarSrc:'', accountMode:'', page:'profile' }); wx.showToast({ title:'已退出登录', icon:'success' }); },
  ...features.methods
});
